---
title: "Software"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(distilltools)
```

## Finpass
A password manager. Log in to sites with ML-based signature verification.

<aside>
 Feb. 2022 - current
</aside>


## Fiduccia and Mattheyses algorithm
The implementation of the [Fiduccia and Mattheyses algorithm(FM algorithm)](../docs/eda/fm-algorithm/index.html) in C++.

<aside>
 Apr. 2022 - May. 2022
</aside>

`r icon_link("github", "Code", "https://github.com/BWbwchen/FM-algorithm")`
`r icon_link("file", "Paper", "https://drive.google.com/file/d/1rMFzvXS4_01GZDeBTs5368wa_QknjzCY/view?usp=sharing")`


## Quine-McCluskey algorithm
The implementation of the Quine-McCluskey algorithm in C++.

<aside>
 Mar. 2022 - Apr. 2022
</aside>

`r icon_link("github", "Code", "https://github.com/BWbwchen/Quine-McCluskey-algorithm")`
`r icon_link("file", "Paper", "https://drive.google.com/file/d/1lmGZnTf4yrZGXXkqLPmlH5gW7t6Krg53/view?usp=sharing")`


## MapReduce
An easy-to-use Map Reduce Go parallel computing framework.

<aside>
 Nov. 2021 - Dec. 2021
</aside>

`r icon_link("github", "Code", "https://github.com/BWbwchen/MapReduce")`
`r icon_link("file", "Document", "https://pkg.go.dev/github.com/BWbwchen/MapReduce")`


## Game cheating detector
Group of 5. Written in Python. An application that **detects whether players are cheating in the game by machine learning**. Won first prize out of 30 teams in a hackathon at NTHU.

<aside>
 Oct. 2021
</aside>

`r icon_link("github", "Code", "https://github.com/Logi-Meichu/Meichu2020_Team_726")`
`r icon_link("globe", "News", "https://www.hccg.gov.tw/ch/home.jsp?id=48&parentpath=&mcustomize=municipalnews_view.jsp&toolsflag=Y&dataserno=202010250004&t=MunicipalNews&mserno=201601300020")`

## Tiny URL service
Written in Go. A scalable, high-performance URL-shortener and API service built with Redis, mongoDB and Zookeeper. Deployed on rancher kubernetes and CI/CD pipeline on self-hosted Gitlab.

<aside>
 Jul. 2021 - Aug. 2021
</aside>

`r icon_link("github", "Code", "https://github.com/BWbwchen/tinyURL")`
`r icon_link("medium", "Article", "https://medium.com/@tim.chenbw/lets-build-a-tinyurl-service-in-golang-47deb5a7904f")`

