- title:  "MapReduce"
  time:   Oct. 2021
  code: https://github.com/BWbwchen/MapReduce
  doc: https://pkg.go.dev/github.com/BWbwchen/MapReduce
  descript: An easy-to-use Map Reduce Go parallel computing framework.

- title:  "Tiny URL service"
  time:   Jul. 2021 - Aug. 2021
  image: https://miro.medium.com/v2/resize:fit:720/format:webp/0*DMBrrskmvS--OVOf.jpg
  code: https://github.com/BWbwchen/tinyURL
  article: https://medium.com/@tim.chenbw/lets-build-a-tinyurl-service-in-golang-47deb5a7904f
  descript: Written in Go. A scalable, high-performance URL-shortener and API service built with Redis, mongoDB and Zookeeper. Deployed on rancher kubernetes and CI/CD pipeline on self-hosted Gitlab.

- title: Game Cheating Detector
  time:   Oct. 2020
  image:  /images/game-cheating-detector.jpg
  code: https://github.com/Logi-Meichu/Meichu2020_Team_726
  article: https://www.hccg.gov.tw/ch/home.jsp?id=48&parentpath=&mcustomize=municipalnews_view.jsp&toolsflag=Y&dataserno=202010250004&t=MunicipalNews&mserno=201601300020
  descript: Group of 5. Written in Python. An application that <strong>detects whether players are cheating in the game by machine learning.</strong> Won first prize out of 30 teams in a hackathon at NTHU.
