---
title: "Kernighan and Lin algorithm (KL algorithm)"
description: |
  Note for EDA partitioning algorithm - Kernighan and Lin algorithm (KL algorithm)

author:
  - name: Bo-Wei Chen
    url: https://BWbwchen.github.io/
date: 2022-03-03
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
  toc_float: 
    collapsed: false
    smooth_scroll: true
draft: false
creative_commons: CC BY
editor_options: 
  markdown: 
    wrap: 72
categories:
  - EDA
  - clustering
  - CAD
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Goal
- Balanced bipartition.
- divided the circuit into 2 equal-sized partitions.

# Rewrite the original circuit graph into edge-weighted undirected graph $G$
- Rewrite the original circuit graph with hyper-edge, and it can share the same node.
	- Edge weight $c(x, y)$ = $\frac{1}{|e| - 1}$ , where $e$ is a hyper-edge and $|e|$ is the size of that hyper-edge.

# Iteratively swap(each iteration is called "pass")
- Randomly bipartitioning the graph $G$ (above rewritten graph)
- Do procedure on the **unmarked** vertex until no **unmarked** exist
	- Compute all the possible swap pairs on the **unmarked** vertex.
		- for vertex $x \in P_1$ , we define:
			- $E_x = \sum_{i \in P_2} c(x, i)$ This is the cut size of outward edge.
			- $I_x = \sum_{i \in P_1} c(x, i)$ This is the cut size of inward edge.
		- for vertex $x \in P_1, y \in P_2$ , if we swap them, the decrease of the cut size between $P_1$ and $P_2$ is :
			- $gain(x, y) = (E_x - I_x - c(x, y)) + (E_y - I_y - c(x, y))$
	- Find the pair with maximum $gain(x, y)$ , swap $(x, y)$ , and then **mark** vertex $x$ and $y$ .
	- Record the $gain(x, y)$ and the current cut size
- If the initial cut size has reduced during the current "pass"
	- Do the other "pass" on the best solution
	- Otherwise, terminate.