---
title: "TimberWolf algorithm"
description: |
  Note for EDA placement algorithm - TimberWolf algorithm

author:
  - name: Bo-Wei Chen
    url: https://BWbwchen.github.io/
date: 2022-03-31
output:
  distill::distill_article:
    toc: true
    toc_depth: 4
    self_contained: false
  toc_float: 
    collapsed: false
    smooth_scroll: true
draft: false
creative_commons: CC BY
editor_options: 
  markdown: 
    wrap: 72
categories:
  - EDA
  - placement
  - CAD
preview: https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_960_720.jpg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- [original paper](https://www.researchgate.net/publication/2981545_The_Timber_Wolf_Placement_and_Routing_Package)

## Goal
- Global and detail **standard cell** placement.

## Algorithm
- Using [Simulate Annealing algorithm](../simulate-annealing-algorithm/index.html)

### State
- random initial placement or wiring configuration
- new state is generated by
	- Swap: exchanging 2 fundamental units
		- (big, small) -> (small, big)
		- big -> small will cause overlap. shift it!(to the less shift amount side)
		- small -> big will make some small gap. do nothing. (It will be used for the later shift for the big block)
	- Move: moving a unit to another row
	- Mirror: Reflect the cell orientation around the y-axis #EDAproblem

### Cost function
- total estimated wire length
- **half-perimeter of the bounding box** of the net.

#### Delta of cost function
- $\Delta C = \Delta W + \Delta W_s$
- $\Delta W$ is the wire length change due to new state. (real result)
	- Calculate the effected nets' change.
- $\Delta W_s$ is the wire length change due to shifting the cells to remove the overlap. (estimated result)
		
##### estimated the $\Delta W_s$ by gradient
- Find the nets, which contain the shifted block, and find the left and right boundary.
- If the shifted block is on the right boundary, the gradient should increase.
- If the shifted block is on the left boundary, the gradient should decrease.
- else, gradient remain unchange.


- $\Delta W_s = \sum_{j \in shifted\_cell} gradient(j) \cdot shift\_amount(j)$

### Overlapping causing by exchanging
- Use penalty function #EDAproblem