---
title: "Elmore Routing Tree Algorithm"
description: |
  Note for EDA routing algorithm - Elmore Routing Tree Algorithm

author:
  - name: Bo-Wei Chen
    url: https://BWbwchen.github.io/
date: 2022-05-05
output:
  distill::distill_article:
    toc: true
    toc_depth: 4
    self_contained: false
  toc_float: 
    collapsed: false
    smooth_scroll: true
draft: false
creative_commons: CC BY
editor_options: 
  markdown: 
    wrap: 72
categories:
  - EDA
  - routing
  - CAD
preview: https://cdn.pixabay.com/photo/2020/09/06/08/00/red-thread-5548304_960_720.jpg
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- Similar to [Bounded Radius Routing Algorithm](../bounded-radius-routing-algorithm/index.html) and [1-Steiner Routing Algorithm](../1-steiner-routing-algorithm/index.html).
- But different in how to select a good node for prim's MST algorithm


## Elmore delay
- $t_{elmore}(n_i) = r_d \cdot C_{n_0} + \sum_{e_v \in path(n_0, n_i)} r_{e_v}(\frac{c_{e_v}}{2}+C_v)$
- $r_d$ is the output resistance
- $C_{n_i}$ is the total capacitance of a subtree of $T$ rooted at $n_i$
- $e_v$ is the edge between vertex $v$ and its parent.
- $r_{e_v}$ and $c_{e_v}$ are calculated by the problem parameter. $\Omega / m(wire length)$ and $F / m(wire length)$


### Elmore Routing Tree Algorithm
- select phase:
- for node $v$ in $MST$ :
	- find the nearest node $u$ of $v$
	- Calculate the elmore delay for $u$
- choose the lowest elmore delay node as the next included node.


### Steiner Elmore Routing Tree Algorithm
- select phase:
- for node $v$ in $MST$ :
	- find the nearest node $u$ of $v$ **and try to add steiner point between u and v**
	- Calculate the elmore delay for $u$
	- **Or connect $u$ and $s$(source) node and calculate the elmore delay.**
- choose the lowest elmore delay node as the next included node.
