---
title: "QEMU"
description: |
  QEMU emulator notes
author:
  - name: Bo-Wei Chen
    url: https://BWbwchen.github.io/
date: 2022-04-22
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
  toc_float: 
    collapsed: false
    smooth_scroll: true
draft: false
creative_commons: CC BY
editor_options: 
  markdown: 
    wrap: 72
categories:
  - VM
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- It is a software emulator
	- What about KVM? Xen?
		- It is a supported module to boost the speed of qemu.
		- Enable by `-enable-kvm`

## Add a virtual disk
```
		  qemu-img create -f qcow2 ubuntu.qcow2 10G
```

### qcow2
- Something like loopback file system.
- It will occupy the space in the disk, If it actually that big.

## Start the QEMU VM
- [qemu 4.2 manual](https://qemu.weilnetz.de/doc/4.2/qemu-doc.html)
```
		  sudo qemu-system-x86_64 -cpu host -enable-kvm \
		  -m 1G -smp 1 \
		  -drive if=virtio,format=qcow2,file=ubuntu.qcow2 \
		  -boot d -cdrom ubuntu-20.04.4-live-server-amd64.iso \
		  -vnc :0
```


## Setup bridge network
- I use ubuntu [netplan](https://netplan.io/), which will generate the corresponding config for specific backend network manger, such as systemd-networkd.
```
		  network:
		      version: 2
		      renderer: networkd
		      ethernets:
		          enp1s0:
		              dhcp4: no
		      bridges:
		          br0:
		              interfaces: [enp1s0]
		              addresses: [192.168.124.76/16]
		              gateway4: 192.168.0.2
		              nameservers:
		                  addresses: [140.114.64.1, 8.8.8.8]
		              dhcp4: no
```
- And launch the vm with flag `-nic tap`


## Setup NFS
- On NFS server:
  ``` bash
  			  $ sudo apt install nfs-kernel-server
  			  $ sudo mkdir /mnt/nfs # setup the sync directory
  			  $ sudo chown nobody:nogroup /mnt/nfs # remove any restriction in the directory
  			  $ sudo chmod 777 /mnt/nfs # give all permission to all the file in the directory
  			  $ sudo vim /etc/exports # Permission for accessing the NFS server
  			  # in /etc/exports
  			  /mnt/nfs  <client ip>(rw,sync,no_subtree_check,no_root_squash)
  			  # /mnt/nfs_share  192.168.43.0/24(rw,sync,no_subtree_check) # allowed an entire subnet to have access to the NFS.
  			  $ sudo exportfs -arv # export the NFS
  ```
- On NFS client:
  ``` bash
  			  $ sudo apt install nfs-common
  			  $ sudo mkdir /mnt/nfs # setup the sync directory
  			  $ sudo mount -t nfs <server ip>:/mnt/nfs /mnt/nfs # mount NFS
  ```


## Monitor
- Add flag `-monitor telnet:127.0.0.1:5500,server,nowait` and you can use telnet to mange the vm.


## Live migration
- It actually stop the VM for a while, but in very short time.
- We will need to add Monitor flag to the source vm.
- Launch the destination vm with migration flag `-incoming tcp:0:4400`
``` bash
		  $ telnet localhost 5500
		  (qemu) migrate -d tcp:<destination ip>:4400
		  (qemu) info migrate
```


## Performance testing


### Sysbench (cpu, memory performance)
- [tutorial](https://linuxhint.com/use-sysbench-for-linux-performance-testing/)
``` bash
			  sysbench cpu --cpu-max-prime=20000 --max-time=20
```
	  
	  
### Iperf (network)
- On the server side :
``` bash
				  iperf -s
```
- On the client side:
``` bash
				  iperf -c <server ip> -t <testing time(s)>
```
