---
title: "Fibonacci"
description: |
  Note for Fibonacci
author:
  - name: Bo-Wei Chen
    url: https://BWbwchen.github.io/
date: 2022-06-17
output:
  distill::distill_article:
    toc: true
    toc_depth: 4
    self_contained: false
  toc_float: 
    collapsed: false
    smooth_scroll: true
draft: false
creative_commons: CC BY
editor_options: 
  markdown: 
    wrap: 72
categories:
  - Fibonacci
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<a id="org52fd914"></a>

# Basic

<div class="org-center">
\begin{align*}
fib(0) &= 0 \\
fib(1) &= 1 \\
fib(n+2) &= fib(n+1) + fib(n) \\
\end{align*}
</div>
```python
def fib(n):
    a = b = 1
    i = 1
    while i < n-1 :
        a, b = a+b, a
        i += 1
    return a
return [fib(x) for x in range(10)]
```
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<tbody>
<tr>
<td class="org-right">1</td>
<td class="org-right">1</td>
<td class="org-right">1</td>
<td class="org-right">2</td>
<td class="org-right">3</td>
<td class="org-right">5</td>
<td class="org-right">8</td>
<td class="org-right">13</td>
<td class="org-right">21</td>
<td class="org-right">34</td>
</tr>
</tbody>
</table>

<a id="orgafd8f42"></a>

There has a formula for fibonacci:

<div class="org-center">
<p>
\(fib(n) = \frac{1}{\sqrt{5}}(\frac{1+\sqrt{5}}{2})^n-\frac{1}{\sqrt{5}}(\frac{1-\sqrt{5}}{2})^n\)
</p>
</div>

But it is **NOT** constant time complexity! Because the precision problem of floating point of computer system, it can NOT calculate the correct answer!


<a id="org56ba125"></a>

# Vorobev equation

The time complexity is $O(logn)$, If we can calculate $f(2n)$ from $f(n)$. The Vorobev equation said:

<div class="org-center">
<p>
\(f(n+k)=f(n-1) \times f(k) + f(n) \times f(k+1)\)
</p>
</div>

We consider: $n := n+1, k := n$:

<div class="org-center">
<p>
\(f(2n+1)=(f(n+1))^2 + (f(n))^2\)
</p>
</div>

<div class="org-center">
<p>
\(f(2n) = f(2n+2) - f(2n+1)\)
</p>
</div>

<div class="org-center">
<p>
\(f(2n) = 2 \times f(n+1) \times f(n) - (f(n))^2\)
</p>
</div>


<a id="orgeb49b99"></a>

# Q-Matrix

from the code [1](#orgafd8f42), we can rewrite the formula as:

<div class="org-center">
\begin{align*}
\begin{pmatrix}
                    F(n+2) \\ F(n+1)
                \end{pmatrix}
=
\begin{pmatrix}
    1 & 1 \\
    1 & 0
\end{pmatrix}

\begin{pmatrix}
    F(n+1) \\ F(n)
\end{pmatrix}
\end{align*}
</div>

With fast doubling:

<div class="org-center">
\begin{align*}
        \begin{bmatrix}
         F(2n+1) \\
         F(2n)
        \end{bmatrix} &=
        \begin{bmatrix}
         1 & 1 \\
         1 & 0
        \end{bmatrix}^{2n}
        \begin{bmatrix}
         F(1) \\
         F(0)
        \end{bmatrix}\\ \\ &=
        \begin{bmatrix}
         1 & 1 \\
         1 & 0
        \end{bmatrix}^n
        \begin{bmatrix}
         1 & 1 \\
         1 & 0
        \end{bmatrix}^n
        \begin{bmatrix}
         F(1) \\
         F(0)
        \end{bmatrix}\\ \\ &=
        \begin{bmatrix}
        F(n+1) & F(n) \\
        F(n) & F(n-1)
        \end{bmatrix}
        \begin{bmatrix}
        F(n+1) & F(n) \\
        F(n) & F(n-1)
        \end{bmatrix}
        \begin{bmatrix}
         1 \\
         0
        \end{bmatrix}\\ \\ &=
        \begin{bmatrix}
         F(n+1)^2 + F(n)^2\\
         F(n)F(n+1) + F(n-1)F(n)
        \end{bmatrix}
        \end{align*}
</div>

We will get:

<div class="org-center">
\begin{align*}
F(2k+1) &= F(k+1)^2+F(k)^2\\
F(2k) &= F(k)[2F(k+1) - F(k)] \\
\end{align*}
</div>

Then we can rewrite the code [1](#orgafd8f42) with fast doubling:
```python
Fast_Fib(n)
    a = 0; b = 1;       // m = 0
    for i = (number of binary digit in n) to 1
        t1 = a*(2*b - a);
        t2 = b^2 + a^2;
        a = t1; b = t2; // m *= 2
        if (current binary digit == 1) // because we only return a
            t1 = a + b; // m++
            a = b; b = t1;
    return a;
```


<a id="orgcce1088"></a>

# Application


<a id="org56af970"></a>

## Pseudo-Random Number Generators (PRNG)

-   [Lagged Fibonacci generator](https://www.wikiwand.com/en/Lagged_Fibonacci_generator)
```
    f[0] = 0;
    f[1] = 1;
    f[i] = (f[i - 1] + f[i - 2]) % 100;
```

